### ISSUE TITLE
[UX Bug] Why don't we have a option to change the favicon of our page?

### ISSUE THREAD

**Issue by saibhaskardevatha** [aniketmandle-sopho/techboard#24]
It would be great, if we can change the favicon according to club.

**Comment by krishraghuram** [comment]
Favicon is the icon in the title bar and any bookmarked links. 

Do you want to change that, or do you want to place your clubs logo in the NavBar?

Request For Comments

**Comment by SaiBhaskarDevatha** [comment]
I want to place my club logo instead of Techboard

**Comment by krishraghuram** [comment]
We can implement this quite easily. 

Firstly, we need to have a logo field in the club_home. Preferably in both colour and b/w formats. 

Then, we can reference that logo from the template, and set it as favicon, in this [line](https://github.com/aniketmandle-sopho/techboard/blob/8c2343f06f16887615cd3235ae08321393ac4871/club_home/templates/club_home/base.html#L14)
